# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Viacheslav Manin
#
# PyInstaller spec for FilterSynthesizer (onedir).
#   build:  pyinstaller --noconfirm --clean FilterSynthesizer.spec
#   output: dist/FilterSynthesizer/FilterSynthesizer.exe  (+ _internal/)
#
# Three things PyInstaller's static analysis CANNOT see on its own, all of
# which produced ModuleNotFoundError only in the frozen build:
#
#  1. streamlit.runtime.scriptrunner.magic_funcs
#     Streamlit's "magic" AST pass injects an import of this at the top of
#     every script it executes. It exists only in generated bytecode, so the
#     module graph never finds it and the EXE dies at app.py line 1.
#
#  2. _pylong  (Python 3.12+)
#     Pure-Python stdlib module that CPython imports LAZILY FROM C once integer
#     operands get large (divmod above _DIV_LIMIT, big str<->int conversion).
#     SymPy's heugcd reaches it on large polynomial coefficients, so the EXE
#     works until a filter produces big enough numbers.
#
#  3. The application's own modules
#     Analysis starts at launcher.py, which imports nothing but streamlit --
#     app.py is handed to Streamlit as a PATH, not imported. Without listing
#     the app modules explicitly, neither they nor their heavy dependencies
#     (numpy/scipy/sympy/plotly/...) enter the graph at all.

from pathlib import Path

from PyInstaller.utils.hooks import collect_all, copy_metadata

ROOT = Path(SPECPATH)

# --- 3) every app module, so its dependency tree is discovered normally ------
# Shipped BOTH as frozen modules (for import) and as .py data files below
# (Streamlit executes app.py from disk). The frozen importer wins on import,
# so the two copies cannot diverge at runtime.
APP_MODULES = sorted(
    p.stem for p in ROOT.glob("*.py")
    if p.name not in {"launcher.py", "FilterSynthesizer.spec", "verify.py"}
)

# --- 1) Streamlit needs its data files AND its distribution metadata --------
# copy_metadata is not optional: streamlit reads its own version through
# importlib.metadata at startup and raises without it.
st_datas, st_binaries, st_hiddenimports = collect_all("streamlit")

datas = list(st_datas)
binaries = list(st_binaries)

hiddenimports = list(st_hiddenimports) + APP_MODULES + [
    "streamlit.runtime.scriptrunner.magic_funcs",
    "_pylong",      # large-int arithmetic, imported from C (3.12+)
    "_strptime",    # same class of lazy C-level import
]

datas += copy_metadata("streamlit")

# app.py must exist as a real file: Streamlit runs it by path.
datas += [(str(ROOT / f"{m}.py"), ".") for m in APP_MODULES]

# User-editable schematics. build.bat also copies this folder NEXT TO the exe;
# launcher.py prefers that copy and falls back to this bundled one.
_svg = ROOT / "Section_Schematic_Diagrams"
if _svg.is_dir():
    datas += [(str(_svg), "Section_Schematic_Diagrams")]


a = Analysis(
    [str(ROOT / "launcher.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "PyQt5", "PySide2", "PySide6", "IPython", "notebook"],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="FilterSynthesizer",
    debug=False,
    strip=False,
    upx=False,          # UPX corrupts some numpy/scipy DLLs; not worth the MB
    console=True,       # keep True until the field reports stop: the console
                        # is where worker tracebacks land
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="FilterSynthesizer",
)
